version: '3.8'

services:
  bot:
    build: .
    container_name: kpt_bot
    restart: always
    volumes:
      - .:/app
    environment:
      - TG_API_TOKEN=${TG_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

