name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_TYPE: kpt-server

jobs:

  Build-client-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build, tag, and push image to Yandex Cloud Container Registry
      run: |
        docker build -t $IMAGE_TYPE:$IMAGE_TAG .
        docker save -o $IMAGE_TYPE.$IMAGE_TAG.tar $IMAGE_TYPE:$IMAGE_TAG

    - name: Copy file to server using appleboy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "$IMAGE_TYPE.$IMAGE_TAG.tar"
        target: "/opt/deploy"

    - name: Deploy to KPT instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: /opt/deploy/server.sh $IMAGE_TYPE.$IMAGE_TAG
