name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  Build-client-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to KPT instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: /opt/deploy/server.sh
    
