name: Stop Service

on: workflow_dispatch

jobs:
  Build-client-image:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to KPT instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: /opt/deploy/stop.sh
    
